### PR TITLE
Jupyter 2.0.1 support

### PR DESCRIPTION
**Pull request by itaistopel**
Hi.

It seems like the installation & the build work well, but instead of searching on files, it doesn't search at all, and shows a part of the commands pellete component.
Could you please take a look?

Thanks.

### CODE REVIEW

**Comment by parente** [comment]
@itaistopel Nice! I'll take a look.

**Comment by parente** [comment]
I have a couple extra commits that should fix the problem. Can you look for the check box in this pull request view that says "Allow maintainers to push to this branch" or something and make sure it's checked? That will allow me to push the commits to your fork / branch. Thanks!

**Comment by itaistopel** [comment]
@parente 
Done. 
I also added you as a collaborator (I sent an [invitation).

**Comment by parente** [comment]
@itaistopel Thanks. Checking that checkbox is all that is needed for me to be able to push to your feature branch. No need to grant me access to your whole fork. 👍 

I pushed the two commits that seem to have everything working end to end here. Updating the Python jupyterlab dependency to `>=2.0.0,<3.0.0a` was the main issue. I also added a few more instructions about how to regenerate the poetry lock file to the README after bumping the Python dependencies.

**Comment by parente** [comment]
I think this is good to go. I'll cut a release of 0.5.0 right after I merge to master. We can iterate in new pull requests if we find issues. Thanks for submitting this one! 🍰 

fixes #11

**Pull request merged**
